spring.application.name=yudha dwi lesmana

# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://ep-spring-star-a1t3pkjz-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_aYiBhf0mn8tW
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# OPTIONAL: Logging for SQL (bisa diaktifkan jika perlu debug)
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
